### ISSUE TITLE
Packing on PyPI

### ISSUE THREAD

**Issue by AntoineAugusti** [MTES-MCT/bulk-geocoding-python-client#1]
Yo,

This looks interesting! Any chance you can push this to PyPI eventually and add tests?

Can help if needed

**Comment by benoitguigal** [comment]
Hello Antoine, the library can now be installed with `pip install bulk_geocoding`.
Tests were already there `bulk_geocoding/test_bulk_geocoding`

**Comment by AntoineAugusti** [comment]
Thanks Benoît 🎉🙏
